[package]
name = "lrm"
version = "0.1.0"
authors = ["Abry Rath <abry.rath@union.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lipsum = "0.6"
clap = {version = "~2.32.0", features = ["yaml"]}
